import type { WorkflowKind } from "./workflows.js";

export type CapabilityClientExposure = "runtime" | "catalog" | "curated-hidden";

export type CapabilityRelation = {
  capabilityId: string;
  primaryTools?: string[];
  supportingTools?: string[];
  workflows?: WorkflowKind[];
  artifactKinds?: string[];
  stateOwners?: string[];
  freshnessChecks?: string[];
  conflictChecks?: string[];
  testFiles?: string[];
  clientExposure?: CapabilityClientExposure;
  noToolReason?: string;
};

export const CAPABILITY_RELATIONS: CapabilityRelation[] = [
  {
    capabilityId: "core.evidence-gated-planning",
    primaryTools: [
      "mission_start",
      "round_start",
      "record_evidence",
      "record_question",
      "update_question",
      "gate_request",
      "emit_plan",
      "mission_status",
    ],
    artifactKinds: ["plan"],
    testFiles: ["tests/tools.test.ts"],
  },
  {
    capabilityId: "orchestration.parallel-sub-orchestrators",
    primaryTools: ["task_register", "schedule_tasks"],
    supportingTools: ["task_status", "task_status_report"],
    testFiles: ["tests/scheduler.test.ts", "tests/tools.test.ts"],
  },
  {
    capabilityId: "orchestration.live-sub-orchestrator-control",
    primaryTools: [
      "control_message",
      "control_ack",
      "task_inbox",
      "task_status",
      "task_status_report",
      "agent_interrupt",
    ],
    stateOwners: ["kernel.tasks"],
    testFiles: ["tests/tools.test.ts"],
  },
  {
    capabilityId: "orchestration.context-compression",
    primaryTools: [
      "optimize_text",
      "optimization_apply",
      "ctx_pack_create",
      "ctx_pack_render",
      "behavior_apply",
    ],
    stateOwners: ["context-store", "optimization-store"],
    testFiles: ["tests/context-store.test.ts", "tests/tools.test.ts"],
  },
  {
    capabilityId: "orchestration.first-party-optimization-primitives",
    primaryTools: ["optimize_text", "optimization_apply", "behavior_apply", "behavior_minimality_review"],
    supportingTools: ["optimization_retrieve"],
    stateOwners: ["optimization-store", "behavior-policy"],
    testFiles: ["tests/optimization.test.ts", "tests/behavior-policy.test.ts"],
  },
  {
    capabilityId: "orchestration.native-context-packs",
    primaryTools: ["ctx_record", "ctx_pack_query", "ctx_pack_create", "ctx_pack_render"],
    supportingTools: ["context_pack_generate"],
    stateOwners: ["context-store"],
    testFiles: ["tests/context-store.test.ts"],
  },
  {
    capabilityId: "orchestration.context-pack-eviction",
    primaryTools: ["ctx_pack_budget_review", "ctx_pack_refresh"],
    stateOwners: ["context-store"],
    testFiles: ["tests/context-store.test.ts"],
  },
  {
    capabilityId: "orchestration.reversible-optimization-pipeline",
    primaryTools: ["optimization_apply", "optimization_retrieve"],
    supportingTools: ["optimization_stats"],
    stateOwners: ["optimization-store"],
    testFiles: ["tests/optimization.test.ts", "tests/optimization-stats.test.ts"],
  },
  {
    capabilityId: "orchestration.external-optimization-adapters",
    primaryTools: [
      "optimization_adapter_register",
      "optimization_adapter_list",
      "optimization_adapter_select",
      "optimization_adapter_run",
    ],
    stateOwners: ["optimization-adapter-registry"],
    testFiles: ["tests/optimization-adapter.test.ts"],
  },
  {
    capabilityId: "orchestration.content-addressed-evidence-cache",
    primaryTools: ["cache_evidence"],
    stateOwners: ["evidence-cache"],
    testFiles: ["tests/evidence-cache.test.ts"],
  },
  {
    capabilityId: "orchestration.reconciliation-engine",
    primaryTools: ["reconcile_artifacts"],
    conflictChecks: ["read-write-set-conflicts"],
    testFiles: ["tests/reconciliation.test.ts"],
  },
  {
    capabilityId: "orchestration.benchmark-runner",
    noToolReason: "Benchmark comparison is executed through package scripts rather than the MCP runtime surface.",
    artifactKinds: ["benchmark_report"],
    testFiles: ["tests/benchmark-runner.test.ts"],
  },
  {
    capabilityId: "orchestration.codex-runtime-adapter",
    primaryTools: ["codex_adapter_config"],
    testFiles: ["tests/codex-adapter.test.ts"],
  },
  {
    capabilityId: "orchestration.external-agent-adapters",
    primaryTools: [
      "agent_register",
      "agent_list",
      "agent_dispatch",
      "agent_dispatch_execute",
      "agent_status",
      "agent_complete",
      "agent_interrupt",
    ],
    stateOwners: ["agent-registry"],
    testFiles: ["tests/agent-adapter.test.ts", "tests/agent-transport.test.ts"],
  },
  {
    capabilityId: "orchestration.printing-press-cli-adapters",
    primaryTools: [
      "printing_press_register",
      "printing_press_list",
      "printing_press_select",
      "printing_press_register_agent",
      "printing_press_verify",
      "printing_press_run",
    ],
    stateOwners: ["printing-press-registry"],
    testFiles: ["tests/printing-press.test.ts"],
  },
  {
    capabilityId: "orchestration.printed-tool-runtime",
    primaryTools: ["printing_press_run", "optimized_command_run"],
    stateOwners: ["printing-press-registry"],
    testFiles: ["tests/tools.test.ts"],
  },
  {
    capabilityId: "orchestration.repo-index-graph",
    primaryTools: [
      "repo_index_build",
      "repo_index_query",
      "repo_index_explain",
      "repo_index_path",
      "repo_index_report",
      "repo_graph_analyze",
      "repo_graph_export",
      "list_communities",
      "get_community",
      "get_surprising_connections",
      "graph_node_semantic_search",
      "list_flows",
      "get_flow",
      "durable_repo_index_query",
    ],
    supportingTools: [
      "repo_graph_refresh_full",
      "repo_graph_refresh_incremental",
      "graph_communities_refresh",
      "graph_node_semantic_index_refresh",
      "flows_refresh",
      "graph_wiki_generate",
    ],
    artifactKinds: ["graphJson", "graphHtml", "graphReport", "graphCommunities", "graphWiki", "executionFlows"],
    freshnessChecks: ["repo-index-fingerprint"],
    testFiles: [
      "tests/repo-index.test.ts",
      "tests/graph-artifacts.test.ts",
      "tests/graph-communities.test.ts",
      "tests/graph-intelligence-tools.test.ts",
    ],
  },
  {
    capabilityId: "orchestration.project-ground-truth-suite",
    primaryTools: [
      "project_contract_detect",
      "dependency_inventory",
      "project_command_map",
      "diagnostics_from_command",
      "diagnostics_from_lsp",
      "diagnostics_record",
      "diagnostics_query",
      "impact_analyze",
      "test_plan_select",
      "verification_run",
      "secret_scan",
      "operation_risk_review",
      "semantic_index_build",
      "semantic_search",
      "lsp_probe",
      "lsp_server_configs",
      "lsp_normalize_location",
      "source_conflicts_analyze",
      "capability_relation_audit",
    ],
    conflictChecks: ["source-conflicts"],
    testFiles: ["tests/source-conflicts.test.ts", "tests/capability-relation-audit.test.ts"],
  },
  {
    capabilityId: "orchestration.anti-slop-lifecycle-gates",
    primaryTools: ["code_smell_scan", "diff_scope_review", "test_quality_review", "coverage_delta_analyze"],
    supportingTools: ["patch_apply", "tool_admission_review", "test_plan_select", "verification_run"],
    conflictChecks: ["diff-scope", "test-quality", "coverage-delta"],
    testFiles: [
      "tests/code-smell-scan.test.ts",
      "tests/diff-scope-review.test.ts",
      "tests/test-quality-review.test.ts",
      "tests/coverage-delta.test.ts",
      "tests/tools.test.ts",
      "tests/tool-registry.test.ts",
    ],
  },
  {
    capabilityId: "orchestration.git-and-release-lifecycle",
    primaryTools: [
      "git_lifecycle_status",
      "git_branch_prepare",
      "git_branch_create",
      "git_commit_prepare",
      "git_commit_create",
      "git_pr_prepare",
      "git_conflict_analyze",
    ],
    supportingTools: ["action_policy_review", "repo_change_scan", "patch_checkpoint"],
    conflictChecks: ["git-conflicts", "git-path-safety"],
    testFiles: ["tests/git-lifecycle.test.ts", "tests/tools.test.ts", "tests/tool-registry.test.ts"],
  },
  {
    capabilityId: "orchestration.dependency-risk-intelligence",
    primaryTools: ["dependency_risk_report", "dependency_audit_live"],
    supportingTools: ["dependency_security_report", "action_policy_review"],
    freshnessChecks: ["dependency-audit-timeout-cap"],
    testFiles: ["tests/dependency-risk.test.ts", "tests/tools.test.ts", "tests/tool-registry.test.ts"],
  },
  {
    capabilityId: "orchestration.docs-sync-gate",
    primaryTools: ["docs_sync_check"],
    supportingTools: ["source_conflicts_analyze", "gate_request"],
    conflictChecks: ["source-conflicts", "missing-docs-update"],
    testFiles: ["tests/docs-sync.test.ts", "tests/tools.test.ts", "tests/tool-registry.test.ts"],
  },
  {
    capabilityId: "orchestration.workspace-graph-intelligence",
    primaryTools: ["workspace_graph_analyze"],
    supportingTools: ["project_contract_detect", "repo_index_build"],
    freshnessChecks: ["allowed-root-boundary"],
    testFiles: ["tests/workspace-graph.test.ts", "tests/tools.test.ts", "tests/tool-registry.test.ts"],
  },
  {
    capabilityId: "orchestration.project-intelligence-sequencing",
    primaryTools: [
      "project_onboard",
      "durable_repo_index_refresh",
      "durable_index_status",
      "durable_index_manifest_refresh",
      "durable_index_manifest_status",
      "durable_repo_index_query",
      "durable_semantic_index_refresh",
      "durable_semantic_search",
      "lsp_session_start",
      "lsp_session_list",
      "lsp_session_status",
      "lsp_session_request",
      "lsp_session_stop",
      "test_impact_analyze_v2",
      "dependency_security_report",
      "action_policy_review",
    ],
    stateOwners: ["durable-index-store", "lsp-session-manager"],
    freshnessChecks: ["durable-index-status"],
    testFiles: ["tests/durable-index-store.test.ts", "tests/lsp-session-manager.test.ts"],
  },
  {
    capabilityId: "orchestration.native-project-intelligence-spine",
    primaryTools: [
      "architecture_map",
      "entrypoint_flow_discover",
      "blast_radius_analyze",
      "context_pack_generate",
      "project_intelligence_snapshot",
    ],
    testFiles: ["tests/project-intelligence-spine.test.ts", "tests/project-intelligence-tools.test.ts"],
  },
  {
    capabilityId: "orchestration.repo-native-coverage-pack",
    primaryTools: ["repo_native_pack_build", "feature_slice_query"],
    supportingTools: [
      "project_onboard",
      "agent_context_prepare",
      "mission_delta_replan",
      "source_conflicts_analyze",
      "capability_relation_audit",
      "test_impact_analyze_v2",
      "test_plan_select",
    ],
    artifactKinds: ["repo_native_pack", "feature_slice"],
    stateOwners: ["repo-native-pack"],
    freshnessChecks: ["repo-native-pack-fingerprint", "relation-test-file-exists"],
    conflictChecks: ["source-conflicts", "coverage-gaps"],
    testFiles: [
      "tests/repo-native-pack.test.ts",
      "tests/repo-native-pack-tools.test.ts",
      "tests/capability-relation-audit.test.ts",
    ],
  },
  {
    capabilityId: "orchestration.domain-indexing-layer",
    primaryTools: [
      "domain_index_refresh",
      "domain_index_status",
      "domain_manifest_generate",
      "domain_manifest_diff",
      "domain_manifest_status",
      "domain_manifest_apply",
      "domain_slice_query",
      "domain_api_query",
      "domain_table_query",
      "domain_index_coverage",
      "domain_index_drift",
      "domain_verification_gate_plan",
    ],
    supportingTools: [
      "repo_native_pack_build",
      "feature_slice_query",
      "durable_repo_index_refresh",
      "durable_index_status",
      "durable_index_manifest_refresh",
      "durable_index_manifest_status",
      "durable_repo_index_query",
      "source_conflicts_analyze",
      "project_contract_detect",
      "test_impact_analyze_v2",
      "test_plan_select",
      "verification_run",
      "discovery_openapi_import",
      "capability_relation_audit",
    ],
    artifactKinds: ["domain_index", "domain_manifest_candidate", "domain_slice", "domain_verification_gate_plan"],
    stateOwners: ["sqlite-domain-index", "domain-index-manifest", "repo-native-pack"],
    freshnessChecks: ["domain-index-status", "domain-index-drift", "durable-index-status"],
    conflictChecks: ["source-conflicts", "domain-coverage-gaps"],
    testFiles: [
      "tests/domain-index-manifest.test.ts",
      "tests/domain-manifest-seeder.test.ts",
      "tests/domain-index.test.ts",
      "tests/sqlite-domain-index.test.ts",
      "tests/domain-index-tools.test.ts",
      "tests/repo-native-pack.test.ts",
      "tests/capability-relation-audit.test.ts",
    ],
  },
  {
    capabilityId: "orchestration.repo-blueprint-compiler",
    primaryTools: ["blueprint_compile_repo", "blueprint_write_artifacts", "blueprint_gate_check"],
    artifactKinds: ["blueprint", "constraints", "agent-context"],
    freshnessChecks: ["blueprint-gate-check"],
    testFiles: ["tests/blueprint.test.ts", "tests/blueprint-files.test.ts"],
  },
  {
    capabilityId: "orchestration.app-process-compiler",
    primaryTools: [
      "app_process_compile",
      "app_process_write_artifacts",
      "app_process_validate",
      "app_process_gate_check",
    ],
    artifactKinds: ["app-process", "roadmap", "backlog", "lifecycle"],
    freshnessChecks: ["app-process-gate-check"],
    testFiles: ["tests/app-process.test.ts", "tests/app-process-files.test.ts"],
  },
  {
    capabilityId: "orchestration.app-process-run-controller",
    primaryTools: [
      "app_process_status",
      "app_process_accept_section",
      "app_process_continue",
      "app_process_record_verification",
    ],
    stateOwners: ["app-process-run-files"],
    freshnessChecks: ["app-process-artifact-freshness"],
    testFiles: ["tests/app-process-run-files.test.ts"],
  },
  {
    capabilityId: "orchestration.native-agent-behavior-verification",
    primaryTools: [
      "agent_remit_create",
      "agent_capability_inventory",
      "agent_behavior_verify",
      "remit_coverage_report",
      "agent_drift_analyze",
      "behavior_findings_render",
    ],
    conflictChecks: ["agent-drift"],
    testFiles: ["tests/agent-behavior-verification.test.ts", "tests/agent-behavior-tools.test.ts"],
  },
  {
    capabilityId: "orchestration.mission-delta-replanning",
    primaryTools: ["mission_delta_replan"],
    testFiles: ["tests/mission-delta-replan.test.ts"],
  },
  {
    capabilityId: "orchestration.lsp-feedback-replanning",
    primaryTools: ["lsp_feedback_replan"],
    supportingTools: ["diagnostics_from_lsp", "diagnostics_record"],
    testFiles: ["tests/mission-delta-tools.test.ts"],
  },
  {
    capabilityId: "orchestration.agent-workspace-memory",
    primaryTools: [
      "agent_workspace_create",
      "agent_workspace_write",
      "agent_workspace_read",
      "agent_workspace_merge",
    ],
    stateOwners: ["agent-workspace-store"],
    conflictChecks: ["workspace-merge-conflicts"],
    testFiles: ["tests/agent-workspace.test.ts"],
  },
  {
    capabilityId: "orchestration.resume-continuation",
    primaryTools: ["resume_record", "resume_checkpoint", "resume_validate", "resume_load"],
    stateOwners: ["resume-store"],
    artifactKinds: ["resume_latest", "resume_checkpoint"],
    freshnessChecks: ["resume-validation-status"],
    testFiles: ["tests/resume-store.test.ts", "tests/runtime-persistence.test.ts", "tests/tools.test.ts"],
  },
  {
    capabilityId: "orchestration.graph-artifact-suite",
    primaryTools: [
      "repo_graph_analyze",
      "repo_graph_export",
      "graph_communities_refresh",
      "list_communities",
      "get_community",
      "get_surprising_connections",
      "graph_wiki_generate",
      "graph_node_semantic_index_refresh",
      "graph_node_semantic_search",
      "flows_refresh",
      "list_flows",
      "get_flow",
      "python_graph_metrics",
      "python_graph_communities",
    ],
    artifactKinds: ["graphJson", "graphHtml", "graphReport", "graphCommunities", "graphWiki", "executionFlows"],
    testFiles: [
      "tests/graph-artifacts.test.ts",
      "tests/graph-communities.test.ts",
      "tests/surprising-connections.test.ts",
      "tests/graph-wiki.test.ts",
      "tests/graph-node-semantic.test.ts",
      "tests/execution-flow-store.test.ts",
      "tests/python-sidecar.test.ts",
    ],
  },
  {
    capabilityId: "orchestration.repo-activity-watch-layer",
    primaryTools: [
      "repo_watch_start",
      "repo_watch_scan",
      "repo_watch_status",
      "repo_watch_stop",
      "repo_change_scan",
      "repo_activity_record",
    ],
    stateOwners: ["repo-activity-store"],
    testFiles: ["tests/repo-activity.test.ts", "tests/repo-activity-tools.test.ts"],
  },
  {
    capabilityId: "orchestration.patch-transactions",
    primaryTools: ["patch_checkpoint", "patch_apply", "patch_status", "patch_rollback"],
    stateOwners: ["patch-transaction-store"],
    artifactKinds: ["patch_checkpoint"],
    testFiles: ["tests/patch-transactions.test.ts"],
  },
  {
    capabilityId: "orchestration.optimized-command-runner",
    primaryTools: ["optimized_command_run", "optimization_stats"],
    supportingTools: ["optimization_apply", "optimization_retrieve"],
    testFiles: ["tests/optimized-command-runner.test.ts", "tests/optimization-stats.test.ts"],
  },
  {
    capabilityId: "orchestration.native-tool-factory",
    primaryTools: ["tool_factory_generate", "tool_factory_validate", "tool_factory_write"],
    artifactKinds: ["tool_scaffold"],
    testFiles: ["tests/tool-factory.test.ts", "tests/tool-factory-handlers.test.ts"],
  },
  {
    capabilityId: "orchestration.local-runner",
    primaryTools: ["orchestration_plan_local", "orchestration_run_local"],
    testFiles: ["tests/orchestration-runner.test.ts"],
  },
  {
    capabilityId: "adaptive.routing-model-selection",
    primaryTools: ["route_mission", "model_profile_select"],
    testFiles: ["tests/adaptive-routing.test.ts", "tests/model-profile.test.ts"],
  },
  {
    capabilityId: "adaptive.connector-registry",
    primaryTools: ["select_connector"],
    testFiles: ["tests/connector-registry.test.ts"],
  },
  {
    capabilityId: "adaptive.graph-first-codebase-query",
    primaryTools: [
      "repo_index_query",
      "repo_index_explain",
      "repo_graph_analyze",
      "list_communities",
      "get_community",
      "get_surprising_connections",
      "graph_node_semantic_search",
      "list_flows",
      "get_flow",
      "durable_repo_index_query",
    ],
    supportingTools: [
      "tool_catalog_query",
      "graph_communities_refresh",
      "graph_node_semantic_index_refresh",
      "flows_refresh",
    ],
    testFiles: ["tests/repo-index.test.ts", "tests/durable-index-store.test.ts", "tests/graph-intelligence-tools.test.ts"],
  },
  {
    capabilityId: "adaptive.agent-facing-routing",
    primaryTools: [
      "tool_layer_map",
      "tool_exposure_profile",
      "tool_catalog_query",
      "tool_admission_review",
      "workflow_start_feature",
      "workflow_fix_bug",
      "workflow_review_pr",
      "workflow_onboard_repo",
      "workflow_write_artifacts",
      "next_best_tool",
      "mission_route",
      "agent_context_prepare",
      "state_maintenance_run",
      "state_maintenance_status",
      "state_maintenance_retry",
    ],
    supportingTools: [
      "context_pack_generate",
      "ctx_pack_budget_review",
      "ctx_pack_refresh",
      "durable_index_status",
      "durable_index_manifest_status",
      "durable_repo_index_query",
      "runtime_behavior_audit",
    ],
    stateOwners: ["context-store", "durable-index-store", "workflow-files"],
    artifactKinds: ["context_pack", "workflow_state", "workflow_resume", "workflow_latest"],
    freshnessChecks: ["durable-index-status", "workflow-artifact-freshness"],
    workflows: [
      "workflow_start_feature",
      "workflow_fix_bug",
      "workflow_review_pr",
      "workflow_onboard_repo",
    ],
    testFiles: ["tests/agent-routing.test.ts", "tests/workflows.test.ts"],
  },
  {
    capabilityId: "adaptive.model-pool",
    primaryTools: ["model_profile_register", "model_profile_select", "conductor_plan"],
    supportingTools: ["model_profile_record_outcome", "model_profile_export_traces"],
    testFiles: ["tests/model-profile.test.ts", "tests/conductor.test.ts"],
  },
  {
    capabilityId: "adaptive.model-profile-learning",
    primaryTools: [
      "model_profile_register",
      "model_profile_select",
      "model_profile_record_outcome",
      "model_profile_export_traces",
    ],
    stateOwners: ["model-profile-registry"],
    testFiles: ["tests/model-profile.test.ts"],
  },
  {
    capabilityId: "adaptive.required-python-runtime",
    primaryTools: [
      "python_sidecar_probe",
      "python_graph_metrics",
      "python_graph_communities",
      "python_trace_summary",
      "media_dependency_report",
    ],
    testFiles: ["tests/python-sidecar.test.ts", "tests/media-ingestion.test.ts"],
  },
  {
    capabilityId: "adaptive.deterministic-conductor",
    primaryTools: ["conductor_plan", "conductor_replay"],
    testFiles: ["tests/conductor.test.ts"],
  },
  {
    capabilityId: "adaptive.durable-behavior-policy",
    primaryTools: [
      "behavior_mode_set",
      "behavior_mode_get",
      "behavior_apply",
      "behavior_minimality_review",
    ],
    stateOwners: ["behavior-policy-store"],
    testFiles: ["tests/behavior-policy.test.ts"],
  },
  {
    capabilityId: "adaptive.native-media-ingestion",
    primaryTools: ["media_dependency_report", "media_ingest_pdf", "media_ingest_image"],
    testFiles: ["tests/media-ingestion.test.ts"],
  },
  {
    capabilityId: "adaptive.shell-hook-manager",
    primaryTools: [
      "shell_hook_discover",
      "shell_hook_plan",
      "shell_hook_install",
      "shell_hook_uninstall",
      "shell_hook_verify",
    ],
    artifactKinds: ["shell_hook_plan"],
    testFiles: ["tests/shell-hooks.test.ts"],
  },
  {
    capabilityId: "adaptive.discovery-tool-generation",
    primaryTools: [
      "discovery_har_import",
      "discovery_openapi_import",
      "discovery_http_crawl",
      "discovery_browser_capture",
      "discovery_tool_spec_generate",
    ],
    supportingTools: ["tool_factory_generate", "tool_factory_validate"],
    testFiles: ["tests/api-discovery.test.ts", "tests/tool-factory.test.ts"],
  },
  {
    capabilityId: "adaptive.learned-orchestration-policy",
    primaryTools: [
      "orchestration_dataset_export",
      "orchestration_policy_train",
      "orchestration_policy_evaluate",
      "orchestration_policy_compare_baselines",
      "orchestration_policy_activate",
      "orchestration_policy_get",
    ],
    stateOwners: ["orchestration-policy-store"],
    testFiles: ["tests/orchestration-learning.test.ts"],
  },
  {
    capabilityId: "adaptive.safe-live-policy-feedback",
    primaryTools: ["orchestration_trace_record", "orchestration_policy_live_feedback"],
    stateOwners: ["orchestration-policy-store"],
    testFiles: ["tests/orchestration-learning.test.ts"],
  },
  {
    capabilityId: "adaptive.orchestration-policy-lab",
    primaryTools: [
      "reasoning_trace_record",
      "reasoning_dataset_export",
      "reasoning_strategy_evaluate",
      "orchestration_policy_evaluate",
    ],
    stateOwners: ["reasoning-research-store", "orchestration-policy-store"],
    testFiles: ["tests/reasoning-research.test.ts"],
  },
  {
    capabilityId: "adaptive.connector-marketplace",
    primaryTools: ["select_connector", "codex_adapter_config"],
    testFiles: ["tests/connector-registry.test.ts", "tests/codex-adapter.test.ts"],
  },
  {
    capabilityId: "adaptive.dynamic-task-spawning",
    primaryTools: ["task_register", "schedule_tasks", "orchestration_plan_local"],
    testFiles: ["tests/scheduler.test.ts", "tests/orchestration-runner.test.ts"],
  },
  {
    capabilityId: "adaptive.model-pool-orchestration",
    primaryTools: ["model_profile_select", "conductor_plan", "conductor_replay"],
    testFiles: ["tests/model-profile.test.ts", "tests/conductor.test.ts"],
  },
  {
    capabilityId: "adaptive.workbench-artifacts",
    primaryTools: ["render_workbench"],
    artifactKinds: ["html_workbench"],
    testFiles: ["tests/workbench.test.ts"],
  },
  {
    capabilityId: "adaptive.rich-artifact-types",
    primaryTools: ["create_artifact"],
    artifactKinds: ["plan", "json_report", "html_workbench", "patch_plan", "benchmark_report"],
    testFiles: ["tests/artifacts.test.ts"],
  },
];

export function toolNamesForCapabilityRelation(relation: CapabilityRelation): string[] {
  return [...(relation.primaryTools ?? []), ...(relation.supportingTools ?? [])];
}
